### ISSUE TITLE
Inquiry about the release of web_demo.py

### ISSUE THREAD

**Issue by zhtjtcz** [pixeli99/TrackDiffusion#2]
I'd like to ask when the `web_demo.py` will be released? 
And using OpenAI key to run the demo is a bit of a tall order for many people, but are there any plans for a simplified version?

**Comment by pixeli99** [comment]
Yes, I am trying to solve the user interaction problem with a lower-cost solution, because our approach requires specifying the trajectory of the entire segment for the target, which is indeed not very convenient for interaction. In the released version, I will use the api of gemini1.0-pro instead of asking everyone to enter the OpenAI key.

This week, web_demo will be released along with the weights.

**Comment by KaiChen1998** [comment]
@zhtjtcz  Thank you for your interest in our work! The training code and the pre-trained checkpoints of both text- and image-conditional TrackDiffusion have been released. The web demo is still on the way. Stay tuned for the latest updates :)!

**Comment by qiuhaining** [comment]
> @zhtjtcz Thank you for your interest in our work! The training code and the pre-trained checkpoints of both text- and image-conditional TrackDiffusion have been released. The web demo is still on the way. Stay tuned for the latest updates :)!

where is the "script.sh"?
I find other bugs:
1、not find "print_log" https://github.com/pixeli99/TrackDiffusion/blob/main/dataset/youtube_loader.py#L221
2、not find I2V codes
3、not find train.json in youtobevis 2019 datasets  from https://opendatalab.com/YouTubeVIS2019/download
