### ISSUE TITLE
Unexpected generated videos..

### ISSUE THREAD

**Issue by aimansnigdha** [pixeli99/TrackDiffusion#7]
Interesting work! Thanks for sharing.

I have used the T2V-weights and followed demo.ipynb:
GT:

![gt_gif_005a527edd_1](https://github.com/pixeli99/TrackDiffusion/assets/27917549/1cd36db1-7c60-4aba-b012-5bf036c6615b)

Generated:
![output_005a527edd](https://github.com/pixeli99/TrackDiffusion/assets/27917549/6362c5c5-7c6d-4e85-810c-e2d067b40617)

GT:
![gt_gif_00917dcfc4_1](https://github.com/pixeli99/TrackDiffusion/assets/27917549/07d90def-a561-4c54-9319-92f935d18530)

Generated:
![output_00917dcfc4](https://github.com/pixeli99/TrackDiffusion/assets/27917549/08599ea5-d299-47fd-9373-a11afde26578)

Please let me know if I should adjust any parameters during testing for better generation. Thanks!

**Comment by pixeli99** [comment]
Hi, I checked this issue, and I'm sorry that I set the wrong width and height in the demo. The correct values should be 384,256 instead of 480,320. I will make this correction.
![output_005a527edd](https://github.com/pixeli99/TrackDiffusion/assets/46072190/6260f655-4f83-40c8-9a72-400c20424c1c)
But even if I use the 480, 320 settings, there is no screen flickering; you should check if the unet weights have been loaded correctly?
If you have any further questions, please feel free to ask me.
